trigger:
  branches:
    include:
    - master
variables:
- name: azureSubscription
  value: 'b6b2f9dd-810a-4b1c-803b-c3cebf0e3d09'
- name: functionAppName
  value: 'azextractfunctionapp'
- name: vmImageName
  value: 'ubuntu-latest'
- name: workingDirectory
  value: '$(System.DefaultWorkingDirectory)'
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Bash@3
      displayName: 'Build extensions'
      inputs:
        targetType: inline
        script: |
          if [ -f extensions.csproj ]
          then
              dotnet build extensions.csproj --runtime ubuntu.16.04-x64 --output ./bin
          fi
        workingDirectory: $(workingDirectory)
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.6'
      inputs:
        versionSpec: 3.6
    - task: Bash@3
      displayName: 'Install application dependencies'
      inputs:
        targetType: inline
        script: |
          pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
        workingDirectory: $(workingDirectory)
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(workingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
    - task: ecdc45f6-832d-4ad9-b52b-ee49e94659be@1
      inputs:
        path: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        artifactName: drop
- stage: Deploy
  displayName: Deploy stage
  dependsOn:
  - Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment:
      name: 'development'
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionAppLinux
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'

